name: Daily Song Add

on:
  schedule:
    - cron: '21 00 * * *' # 12.21AM CST
      timezone: 'America/Chicago'
  workflow_dispatch:

jobs:
  add-song:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore Spotify cache       
        run: echo '${{ secrets.SPOTIFY_CACHE }}' > .cache

      - name: Run script                  
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}  
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
        run: python wf_record_top_song.py
